[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vii-assistant"
version = "0.1.0"
# readme = "README.md"
requires-python = ">=3.13"

dependencies = [
  "PySide6",
  "Pillow",
  "numpy",
  "requests",
  "click",
  "python-fusion",
  "pynput",
  "pytesseract",
  "websockets",
  "httpx",
  "json-repair",
]

[project.scripts]
vii-assistant = "assistant.main:main"

[tool.setuptools]
packages = ["assistant"]


[project.optional-dependencies]
inference = [
  "fastapi",
  "uvicorn",
  "qwen-vl-utils",
  "transformers",
  "torch",
  "torchvision",
  "torchaudio",
  "torchcodec",
  "onnxruntime-gpu",
]
all = ["vii-assistant[inference]"]
dev = ["pytest", "black", "isort", "pre-commit"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88
combine_as_imports = true
